import { Inter as FontSans } from "next/font/google"
import './globals.css'
import { cn } from "@/lib/utils"
import { Providers } from "@/providers/providers"
 
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
     	<body className={cn("font-sans antialiased",fontSans.variable)}>
			<Providers>
				{children}
			</Providers>
		</body>
    </html>
  )
}
